### ISSUE TITLE
Misspeled embedding file name 

### ISSUE THREAD

**Issue by kacpnowak** [clessig/atmorep#12]
In the atmorep_model.py [line 284](https://github.com/clessig/atmorep/blob/c680d90ba69a816958919c375ca330ff433c066c/atmorep/core/atmorep_model.py#L284C29-L284C46) embedding files are loaded under the name "_embed_token_info", however in [line 455](https://github.com/clessig/atmorep/blob/c680d90ba69a816958919c375ca330ff433c066c/atmorep/core/atmorep_model.py#L455) are saved as "_embeds_token_info" causing a crash when multiformers are used

**Comment by kacpnowak** [comment]
I've also encoutered error with keys not matching: 
RuntimeError: Error(s) in loading state_dict for Linear:
3: 	Missing key(s) in state_dict: "weight", "bias".
3: 	Unexpected key(s) in state_dict: "0.weight", "0.bias".

To solve it one can add "strict=False" in [line 286](https://github.com/clessig/atmorep/blob/c680d90ba69a816958919c375ca330ff433c066c/atmorep/core/atmorep_model.py#L286)

**Comment by clessig** [comment]
Ok, we don't see the issue with multiformers not loading. Which branch are you on?

@iluise : have you seen a problem with multiformers?

**Comment by iluise** [comment]
Hi this should have been fixed in this PR: https://github.com/clessig/atmorep/pull/37. 
Closing the issue now. please let me know if you still have problems.
