### ISSUE TITLE
Hard-coded paths in code

### ISSUE THREAD

**Issue by mlangguth89** [clessig/atmorep#13]
There are several points in the code where paths are hard-coded and paths defined in `config.py` remain unused. The usage of relative paths for the `data`, `result` and `model`-directory furthermore induces a constraint on the current working directory, i.e. from where the runscripts are executed.

Examples for hard-coded paths:
- `./atmorep/datasets/normalizer_local.py`, l.27
- `./atmorep/core/evaluator.py`, l.93
- `./atmorep/applications/downscaling_trainer.py`, l.284 (branch: [lessig_dev](https://github.com/clessig/atmorep/tree/lessig-dev))

This issue is also related to #10.

**Comment by clessig** [comment]
Fixed. 

@iluise : can you please fix it in the normalizer code when you are re-working it.
