### ISSUE TITLE
Data loader performance needs to be optimzied

### ISSUE THREAD

**Issue by clessig** [clessig/atmorep#20]
The processing in the data loader is too slow so that training shows "hiccups" in the samples per second as can be seen here:

epoch: 0 [2/1536 (0%)]  Loss: 1.03558 : 0.66213 :: 0.56543 (15.16 s/sec)
epoch: 0 [3/1536 (0%)]  Loss: 1.18547 : 0.84758 :: 0.56201 (18.37 s/sec)
epoch: 0 [4/1536 (0%)]  Loss: 1.21571 : 0.91292 :: 0.55908 (18.44 s/sec)
epoch: 0 [5/1536 (0%)]  Loss: 1.00771 : 0.63998 :: 0.55566 (15.96 s/sec)
epoch: 0 [6/1536 (0%)]  Loss: 1.10328 : 0.74153 :: 0.55322 (20.02 s/sec)
epoch: 0 [7/1536 (0%)]  Loss: 1.06878 : 0.69810 :: 0.55078 (18.96 s/sec)
epoch: 0 [8/1536 (1%)]  Loss: 0.95480 : 0.54988 :: 0.54688 (19.51 s/sec)
epoch: 0 [9/1536 (1%)]  Loss: 1.07270 : 0.70618 :: 0.54590 (1.78 s/sec)
epoch: 0 [10/1536 (1%)] Loss: 0.92099 : 0.52171 :: 0.54297 (16.97 s/sec)
epoch: 0 [11/1536 (1%)] Loss: 1.01511 : 0.64583 :: 0.54004 (18.51 s/sec)
epoch: 0 [12/1536 (1%)] Loss: 0.92716 : 0.54073 :: 0.53955 (18.49 s/sec)
epoch: 0 [13/1536 (1%)] Loss: 1.06327 : 0.70399 :: 0.53711 (17.00 s/sec)
epoch: 0 [14/1536 (1%)] Loss: 0.97117 : 0.62728 :: 0.53369 (18.69 s/sec)
epoch: 0 [15/1536 (1%)] Loss: 1.06912 : 0.70558 :: 0.53369 (18.08 s/sec)
epoch: 0 [16/1536 (1%)] Loss: 0.89139 : 0.49484 :: 0.53027 (18.36 s/sec)
epoch: 0 [17/1536 (1%)] Loss: 0.91976 : 0.55289 :: 0.52734 (1.74 s/sec)
epoch: 0 [18/1536 (1%)] Loss: 0.90912 : 0.52182 :: 0.52295 (17.84 s/sec)
epoch: 0 [19/1536 (1%)] Loss: 0.97324 : 0.61002 :: 0.52197 (18.94 s/sec)

Optimize performance to fix this.

**Comment by iluise** [comment]
should we close this maybe?
