### ISSUE TITLE
Set up templates for issues

### ISSUE THREAD

**Issue by clessig** [clessig/atmorep#21]
Set up templates for bugs and features requests for the AtmoRep git repo. Should we also have templates for scientific features?

**Comment by iluise** [comment]
something like this? 

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/b3c8aaf9-2b6a-434e-b66e-877f710a8cc3">

1) settings
2) scroll down a bit until the section "features" 
3) issues: "cluck on "get organised with issues templates" -> set up templates
4) add template -> select 


"Bug" and "Features" are automatically generated and we can leave them like this I guess. For the scientific issue, please copy the text below:

**Describe the topic**
A clear and concise description of the scientific topic you want to discuss.

**Describe the technical developments**
A clear and concise description of the technical advancements needed to make this happen. Ideally as bullet points

**Additional context**
Add any other context or screenshots about the discussed topic here. 

** Related issues**
link here the issues related to this scientific discussion.

**Comment by clessig** [comment]
Something like this, doesn't need to be very elaborate but some standard structure is useful (and just as a reminder for what info to include):

<img width="930" alt="Screenshot 2024-09-10 at 08 12 26" src="https://github.com/user-attachments/assets/198c715d-f986-400b-ad72-10dd650852dd">

<img width="971" alt="Screenshot 2024-09-10 at 08 13 00" src="https://github.com/user-attachments/assets/14d1e813-83ad-4a1d-8d47-51c044938bb2">

**Comment by iluise** [comment]
Done, please take a look and let me know if we should add other issues.

**Comment by clessig** [comment]
I think the list is fine for now. Maybe in the future it would be nice to have one for a downstream application.

There are some "." missing for Bug and Feature, always the last sentence in the line. Can we fix this. And we can close the issue.

**Comment by iluise** [comment]
done in `iluise/head` now. closing the issue.
