### ISSUE TITLE
Incorrect path to json file in Config load_json

### ISSUE THREAD

**Issue by kacpnowak** [clessig/atmorep#34]
In [this line](https://github.com/clessig/atmorep/blob/1fbb02a008688bd7068dd0762f5e272deada3e0d/atmorep/utils/utils.py#L111C44-L111C46) second part of the path starts with "/", which results in the first part of the path being ignored and causes crash when loading json file:
Could not find fname due to [Errno 2] No such file or directory: '/models/idbijcw27f/model_idbijcw27f.json'. Aborting.

**Comment by clessig** [comment]
Do you have a fix? Then you could open a PR.

**Comment by kacpnowak** [comment]
Yes, I'll do it

**Comment by clessig** [comment]
Please make sure that you create a new branch so that we can merge back and that it's based on develop.
