### ISSUE TITLE
Incorporate Orography and Land-Sea Mask Variables

### ISSUE THREAD

**Issue by nish03** [clessig/atmorep#42]
To improve the accuracy and geographical relevance of the AtmoRep foundation model, it would be beneficial to incorporate two key static variables from ERA5, i.e., orography (surface elevation) and the land-sea mask. Currently, AtmoRep doesn't use these inputs, despite their role in influencing weather patterns. By adapting the model's architecture to include these variables, we can better capture terrain-sensitive and coastal environments, potentially enhancing the model's predictive capabilities.

**Comment by clessig** [comment]
From our experience, these variables won't make a difference: the model learns it from the dynamical variables. E.g. when one looks at the stddev plots, all orographic features are clearly visible. This is also consistent what we observed at ECMWF with downscaling: with a model with a sufficiently complete state of the dynamical system and a sufficiently large training data set, orography, land-sea mask etc do not improve scores any longer.
