### ISSUE TITLE
[BUG] Process out of memory when using fesom data and more than 2 workers

### ISSUE THREAD

**Issue by kacpnowak** [clessig/atmorep#49]
**Description**
In my  [branch](https://github.com/clessig/atmorep/tree/nowak-22-add-support-for-fesom-files) I don't know why memory is exceeded when using more than two workers. We put 1 degree fesom data into format mimicking era5:

```
ds['data'].info
Name               : /data
Type               : zarr.core.Array
Data type          : float32
Shape              : (22280, 4, 47, 170, 360)
Chunk shape        : (8, 4, 47, 170, 360)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 1025379072000 (955.0G)
No. bytes stored   : 471132665050 (438.8G)
Storage ratio      : 2.2
Chunks initialized : 2785/2785
```

I attach logs
[atmorep-slurm_atmorep.sh.12968591.err.txt](https://github.com/user-attachments/files/17134480/atmorep-slurm_atmorep.sh.12968591.err.txt)
[output_12968591.txt](https://github.com/user-attachments/files/17134481/output_12968591.txt)

**To Reproduce**

1. Set num_loader_workers to more than 2 in train.py
2. run slurm_atmorep.sh
3. See error

**Expected behavior**
It should start training instead of crashing 

**Hardware and environment:**
 - System: DKRZ
 - Runtime: sbatch
 - Special branch: [fesom_support](https://github.com/clessig/atmorep/tree/nowak-22-add-support-for-fesom-files)
 - Python Version: 3.10.10

**Additional context**
In my earlier prototype there was no problem with training with this setup, but the file was structured differently. Each field was a separate array withing zarr. Data loader was modified to accommodate this change: `data = self.ds[grib_index[field_info[0]]][idxs_t]`

```
 ds['temp'].info
Name               : /temp
Type               : zarr.core.Array
Data type          : float32
Shape              : (22645, 48, 170, 360)
Chunk shape        : (8, 48, 170, 360)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=3, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 266087808000 (247.8G)
No. bytes stored   : 119017103556 (110.8G)
Storage ratio      : 2.2
Chunks initialized : 2831/2831
```

**Comment by clessig** [comment]
I assume it is CPU memory that is exceeded? How much RAM do the jobs on DKRZ have? Are you using all available one?

**Comment by kacpnowak** [comment]
Yes, its CPU memory. DKRZ has 512 GB per node, while using A100 with 80 GB. Sstats showed usage of of like 600 GB of RAM. I tried using 1 task per node but it didn't help

**Comment by clessig** [comment]
What's the batch size you are using?

**Comment by kacpnowak** [comment]
By default 96, but I've tested 16 with 8 workers and the result is identical

**Comment by clessig** [comment]
What's the (approximate effective) grid resolution of the FESOM data?

**Comment by kacpnowak** [comment]
It's daily data on a 1 degree grid

**Comment by iluise** [comment]
Hi kacper, 
what's the size of the loaded cube? Is that what you expect?

also, side question: why `n_size : [30, 30, 30]` if
 
fields : [['temp', [1, 1024, [], 0], [1], [5, 3, 3], [3, 10, 10], [0.5, 0.9, 0.2, 0.05]]]

shouldn't be n_size = 15 in time if you have daily data?

**Comment by kacpnowak** [comment]
Thanks for pointing this out! It definitely should be as you described.

I'm sure it's related to creating mask while training. I've found a bug with inverted mask for training and fixing it made things better. Now it crashes at 7 and more workers instead of 3. It's really bizarre to me, but at least models are training

**Comment by kacpnowak** [comment]
I found that using mask for loss function is currently unnecessary so this is not a problem anymore. I think this issue can be closed

**Comment by iluise** [comment]
Hi, I am closing the issue, but can you please explain what does it mean in practice using mask for the loss function?
Thanks!
