### ISSUE TITLE
[BUG] Duplicate GPU detected 

### ISSUE THREAD

**Issue by sascholle** [clessig/atmorep#77]
**Describe the bug**
train.py crashes with this error message repeated for the all ranks:

torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:317, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.21.5
3: ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
3: Last error:
3: Duplicate GPU detected : rank 3 and rank 0 both on CUDA device 3000

**Hardware and environment:**
 - System: dkrz Levante
 - Runtime: sbatch
 - Special branch: main
 - Python Version: 3.10.10 

SBATCH file: 
#!/bin/bash -x
#SBATCH --account=ab1412
#SBATCH --partition=gpu
#SBATCH --time=00:10:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:4
#SBATCH --chdir=.
#SBATCH --output=logs/atmorep-%x.%j.out
#SBATCH --error=logs/atmorep-%x.%j.err

## import modules at dkrz
module load python3/2023.01-gcc-11.2.0 nvhpc/23.9-gcc-11.2.0
source pyenv/bin/activate

export UCX_TLS="^cma"
export UCX_NET_DEVICES=mlx5_0:1,mlx5_1:1,mlx5_4:1,mlx5_5:1

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CUDA_VISIBLE_DEVICES=0,1,2,3

## so processes know who to talk to
export MASTER_ADDR="$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)"
echo "MASTER_ADDR: $MASTER_ADDR"

export NCCL_DEBUG=TRACE
echo "nccl_debug: $NCCL_DEBUG"

## work-around for flipping links issue on JUWELS-BOOSTER
export NCCL_IB_TIMEOUT=250
export UCX_RC_TIMEOUT=16s
export NCCL_IB_RETRY_CNT=50

echo "Starting job."
echo "Number of Nodes: $SLURM_JOB_NUM_NODES"
echo "Number of Tasks: $SLURM_NTASKS"
date

export SRUN_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}

CONFIG_DIR=${SLURM_SUBMIT_DIR}/atmorep_train_${SLURM_JOBID}
mkdir ${CONFIG_DIR}
cp ${SLURM_SUBMIT_DIR}/atmorep/core/train.py ${CONFIG_DIR}
echo "${CONFIG_DIR}/train.py"
srun --label --cpu-bind=v --accel-bind=v ${SLURM_SUBMIT_DIR}/pyenv/bin/python -u ${CONFIG_DIR}/train.py > output/output_${SLURM_JOBID}.txt

echo "Finished job."
sstat -j $SLURM_JOB_ID.batch   --format=JobID,MaxVMSize
date

![image](https://github.com/user-attachments/assets/e053ef1d-a76f-4e84-86b9-470e83eae182)

**Comment by clessig** [comment]
Did you run with the slurm script or interactive?

**Comment by sascholle** [comment]
Slurm script - I've edited the issue to include the .sh script above now

**Comment by clessig** [comment]
@kacpnowak : you are running on Levante. Any changes necessary?

**Comment by ankitpatnala** [comment]
@sascholle set this parameter #SBATCH --ntasks-per-node=1

**Comment by sascholle** [comment]
Worked thanks!

**Comment by sascholle** [comment]
Resolved

**Comment by mlangguth89** [comment]
@clessig, @sascholle and @ankitpatnala 
`#SBATCH --ntasks-per-node=1` will leave three out of four GPUs idle on the compute node.
With two nodes, only two out of eight GPUs are used, which is fairly inefficient.
Isn't there a smarter way to perform data parallelized training?
Related to this is that the local rank of the GPU is set in the configuration of the variable, see [here](https://github.com/clessig/atmorep/blob/4d533eb22aaf8404f6c905c65c1506ed8d6f92f8/atmorep/core/train.py#L108).

**Comment by sascholle** [comment]
@ankitpatnala just wanting to follow up on @mlangguth89 comment, any ideas on the root cause?

**Comment by ankitpatnala** [comment]
It is primarily due to hardcoding of the device id in the cf.fields parameter. If we remove that for singleformer, then we could do single node multi GPU ddp training.

**Comment by sascholle** [comment]
@clessig yes the fix works with --ntasks-per-node=1, but I'm still just working with a small data subset. I'll loop back to this issue with the JSC or Levante people when I need to scale up and have a more efficient pipeline. Thanks for the quick help @ankitpatnala, @mlangguth89 and @clessig.
