### ISSUE TITLE
Model config json is not loaded correctly

### ISSUE THREAD

**Issue by kacpnowak** [clessig/atmorep#9]
In Config class, FileNotFoundError is not caught in [load_json method](https://github.com/clessig/atmorep/blob/c680d90ba69a816958919c375ca330ff433c066c/atmorep/utils/utils.py#L110), resulting in a crash when file is written to results. Here's a possible fix: [stack post](https://stackoverflow.com/questions/15032108/pythons-open-throws-different-errors-for-file-not-found-how-to-handle-b)

**Comment by clessig** [comment]
Exception is not caught, indeed. But when it is in load_json then it cannot happen when it is written to results? Is it because the json does not exist or there is a missing folder?
